### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by bigguystevieb** [glixzzy/quizlet-hack#1]
Hey @glixzzy I found an ISSUE an this, I hope not to be a pain in the neck going around and using all these but I have a video this time, take a look.

Sorry for being a pain.

https://user-images.githubusercontent.com/91082938/151483098-bca9309c-0df3-41cf-a1e0-93eb8b9bb2ea.mp4

**Comment by glixzzy** [comment]
Oh very interesting, thank you for reporting this! I will fix it in the morning.

**Comment by glixzzy** [comment]
Should be fixed now.
